### PR TITLE
Make use of ehanced package rename functionality introduced in refactoring-library

### PR DESCRIPTION
**Pull request by mlangc**
This PR enhances the IDE to make use of enhanced package rename functionality introduced in https://github.com/scala-ide/scala-refactoring/pull/181. Further details can be found in the linked PR.

See [#1002769](https://scala-ide-portfolio.assembla.com/spaces/scala-ide/tickets/1002769-package-renaming-error-in-the-package-object/details#).

### CODE REVIEW

**Comment by mlangc** [comment]
> [ERROR] /localhome/jenkinside/workspace/ghprb-scala-ide-multi-conf/eclipse_platform/eclipse-neon/scala-ide/org.scala-ide.sdt.core/src/org/scalaide/refactoring/internal/ScalaIdeRefactoring.scala:146: error: not found: type MoveToDirChange

This does not yet build, because it relies on changes in https://github.com/scala-ide/scala-refactoring/issues/181.

**Comment by sschaef** [comment]
retest this please

File: org.scala-ide.sdt.core/src/org/scalaide/util/eclipse/FileUtils.scala [hunk 1]
```diff
@@ -98,11 +99,14 @@ object FileUtils {
    * file might "mounted" under multiple locations in the Eclipse file system, the `prefix`
    * path is used disambiguate.
    */
-  def resourceForPath(location: IPath, prefix: IPath = Path.EMPTY): Option[IFile] = {
-    val resources = Try(ResourcesPlugin.getWorkspace.getRoot.findFilesForLocationURI(URIUtil.toURI(location))).getOrElse(Array())
+  def fileResourceForPath(location: IPath, prefix: IPath = Path.EMPTY): Option[IFile] = {
```
Comment (sschaef) [inline org.scala-ide.sdt.core/src/org/scalaide/util/eclipse/FileUtils.scala]: This changes actually the public API but I guess no one depends on this code anyway so we can just ignore it ;)

File: org.scala-ide.sdt.core/src/org/scalaide/util/eclipse/FileUtils.scala [hunk 2]
```diff
@@ -98,11 +116,22 @@ object FileUtils {
...
+  private def containerResourceForPath(location: String, prefix: IPath = Path.EMPTY): Option[IContainer] = {
+    containerResourceForPath(Path.fromOSString(location), prefix)
+  }
+
+  private def containerResourceForPath(location: IPath, prefix: IPath): Option[IContainer] = {
+    val resources = Try(workspaceRoot.findContainersForLocationURI(URIUtil.toURI(location))).getOrElse(Array())
+    resources.find(r => prefix.isPrefixOf(r.getFullPath))
+  }
+
+  private def workspaceRoot = ResourcesPlugin.getWorkspace.getRoot
```
Comment (wpopielarski) [inline org.scala-ide.sdt.core/src/org/scalaide/util/eclipse/FileUtils.scala]: not to nag you but `EclipseUtil` defines `workspaceRoot` too

File: org.scala-ide.sdt.core/src/org/scalaide/util/eclipse/FileUtils.scala [hunk 3]
```diff
@@ -104,6 +121,14 @@ object FileUtils {
     resources.find(prefix isPrefixOf _.getFullPath)
   }
 
+  private def containerResourceForPath(location: String, prefix: IPath = Path.EMPTY): Option[IContainer] = {
+    containerResourceForPath(Path.fromOSString(location), prefix)
+  }
+
+  private def containerResourceForPath(location: IPath, prefix: IPath): Option[IContainer] = {
+    val resources = Try(workspaceRoot.findContainersForLocationURI(URIUtil.toURI(location))).getOrElse(Array())
```
Comment (sschaef) [inline org.scala-ide.sdt.core/src/org/scalaide/util/eclipse/FileUtils.scala]: I don't like that an exception is ignored. Which exceptions do you expect here?

**Comment by sschaef** [comment]
scala-refactoring needs to be updated in the pom.xml to 0.13

**Comment by mlangc** [comment]
I'll be off for a few days, but I'll look at this the next weekend (vers. 11th February) !

File: org.scala-ide.sdt.core/src/org/scalaide/util/eclipse/FileUtils.scala (hunk 2 above)
Comment (mlangc) [inline org.scala-ide.sdt.core/src/org/scalaide/util/eclipse/FileUtils.scala]: Thanks for pointing out!

File: org.scala-ide.sdt.core/src/org/scalaide/util/eclipse/FileUtils.scala (hunk 3 above)
Comment (mlangc) [inline org.scala-ide.sdt.core/src/org/scalaide/util/eclipse/FileUtils.scala]: Honestly, I don't really know, since this code originally is from @dragos. I refactored this a bit, so that we can find out (exceptions are now logged).

File: .gitignore [hunk 4]
```diff
@@ -7,3 +7,4 @@ org.scala-ide.sdt.update-site/site.xml
 .idea
 .metadata
 *~
+org.scala-ide.sbt.build
```
Comment (sschaef) [inline .gitignore]: The change in this commit is not needed. The `sbt.build` dir is no longer used. You can remove it from your repo.

Comment (mlangc) [inline .gitignore]: Thanks for the hint; I've just removed it.

**Comment by sschaef** [comment]
Alright, thanks for the contribution!
